name: rgb_cli
version: 1.0.5
homepage: https://pub.dev/packages/rgb_cli
description: CLI tool for the GetX RGB ecosystem and codebase
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  ansicolor: ">=2.0.3 <3.0.0"
  collection: ">=1.18.0 <1.19.1"
  dart_style: ">=3.1.2 <4.0.0"
  dcli: ">=6.0.5 <7.0.5"
  http: ">=1.1.0 <1.5.0"
  intl: ">=0.18.0 <0.20.2"
  meta: ">=1.14.0 <2.0.0"
  path: ">=1.8.0 <2.0.0"
  process_run: ">=0.13.0 <1.0.0"
  pubspec_parse: ">=1.2.0 <2.0.0"
  pub_semver: ">=2.1.4 <3.0.0"
  recase: ">=4.1.0 <5.0.0"
  version: ">=3.0.2 <4.0.0"
  yaml: ">=3.1.2 <4.0.0"

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0

executables:
  rgb: rgb
